version: "3"

services:
  antink-server:
    build: .
    privileged: true
    volumes:
      - ./it24_host:/app/it24_host         
      - ./antink-logs:/app/antink-logs     
      - antink_mount:/antink_mount         
    command: ["./antink", "/antink_mount"]

  antink-logger:
    image: busybox
    volumes:
      - ./antink-logs:/app/antink-logs
    command: ["sh", "-c", "tail -f /app/antink-logs/it24.log"]

volumes:
  antink_mount: